Add API test
BIBSYSDEV/nva-channel-registry pull request #20
Opened 2021-04-20 15:44 UTC by brinxmat

This adds four endpoints:

- Search for journals with parameters query and year
  - if year is unspecified, current year is assumed
- Search for publishers with parameters query and year
-  if year is unspecified, current year is assumed
- direct URL for single journal in a given year
- direct URL for single publisher in a given year

2021-04-21 06:57 UTC, terjehell approved these changes, later dismissed

2021-04-21 08:41 UTC, garshol commented on test/test_data/journal_search_body.json
> +      "dbhId": "446885",
channelId?

2021-04-21 10:48 UTC, axthosarouris commented on test/api-test.feature
> +    Given url <VALID_URL>
VALID_URL_WITH_START_PARAMETER

2021-04-21 10:49 UTC, axthosarouris approved these changes, later dismissed

2021-04-22 14:47 UTC, sarahse commented on test/api-test.feature
> +    And match response.hits.length < 11
er `<11` bedre enn `<=10`?

2021-04-22 14:50 UTC, sarahse submitted a review, later dismissed

2021-04-26 10:57 UTC, axthosarouris requested changes

2021-04-26 10:57 UTC, axthosarouris commented on test/api-test.feature
> +    Then status 406
From Mozilla's documentation I think this is a 405- Method-not-allowed. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)

2021-04-26 10:57 UTC, axthosarouris commented on test/api-test.feature
> +    Then status 406
Should we also supply the acceptable types?

2021-04-26 15:17 UTC, axthosarouris approved these changes

2021-04-26 18:08 UTC, merged